src/Entity/Race.php
<?php

namespace App\Entity;

use App\Repository\RaceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RaceRepository::class)]
#[UniqueEntity(fields:["name"], message: "erreur: cette combinaison d'amure existe déjà")]
#[UniqueEntity(fields:["slug"], message: "erreur: cette combinaison d'amure existe déjà")]
class Race
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\Column(length: 30)]
    #[Assert\Length(
        min:3,
        max:30,
        maxMessage: "Le nom doit faire {{ limit }} caractères maximum.",
        minMessage: "Le nom doit faire {{ limit }} caractères minimum."
    )]
    #[Assert\NotBlank(message: "vous devez obligatoirement metre un nom, celui-ci doit faire entre 3 et 50 caractere")]
    private ?string $name;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $bonus;

    #[ORM\Column(length: 255)]
    private ?string $slug;

    #[ORM\Column(type: Types::TEXT, nullable: false)]
    private ?string $SocialAbility;

    #[ORM\Column(type: Types::TEXT, nullable: false)]
    private ?string $physicalAbility;

    #[ORM\Column(nullable: false)]
    #[Assert\Positive(message:"La taille minimum doit être un nombre supérieur à zéro.")]
    private ?int $minHeight;

    #[ORM\Column(nullable: false)]
    #[Assert\Positive(message:"La taille maximum doit être un nombre supérieur à zéro.")]
    private ?int $maxHeight;

    #[ORM\Column(nullable: false)]
    #[Assert\Positive(message:"Le poids moyens doit être un nombre supérieur à zéro.")]
    private ?int $averageWheight;

    #[ORM\Column(nullable: false)]
    #[Assert\Positive(message:"l'age adulte doit être un nombre supérieur à zéro.")]
    private ?int $adulthood;

    #[ORM\Column(nullable: false)]
    #[Assert\Positive(message:"La durèe de vie doit être un nombre supérieur à zéro.")]
    private ?int $lifetime;

    public function getId(): ?int { return $this->id; }

    public function getName(): ?string { return $this->name; }
    public function setName(string $name): static
    {
        $this->name = $name;
        return $this;
    }

    public function getDescription(): ?string { return $this->description; }
    public function setDescription(?string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getBonus(): ?string { return $this->bonus; }
    public function setBonus(?string $bonus): static
    {
        $this->bonus = $bonus;
        return $this;
    }

    public function getSlug(): ?string { return $this->slug; }
    public function setSlug(string $slug): static
    {
        $this->slug = $slug;
        return $this;
    }

    public function getSocialAbility(): ?string { return $this->SocialAbility; }
    public function setSocialAbility(?string $SocialAbility): static
    {
        $this->SocialAbility = $SocialAbility;
        return $this;
    }

    public function getPhysicalAbility(): ?string { return $this->physicalAbility; }
    public function setPhysicalAbility(?string $physicalAbility): static
    {
        $this->physicalAbility = $physicalAbility;
        return $this;
    }

    public function getMinHeight(): ?int { return $this->minHeight; }
    public function setMinHeight(?int $minHeight): static
    {
        $this->minHeight = $minHeight;
        return $this;
    }

    public function getMaxHeight(): ?int { return $this->maxHeight; }
    public function setMaxHeight(?int $maxHeight): static
    {
        $this->maxHeight = $maxHeight;
        return $this;
    }

    public function getAverageWheight(): ?int { return $this->averageWheight; }
    public function setAverageWheight(?int $averageWheight): static
    {
        $this->averageWheight = $averageWheight;
        return $this;
    }

    public function getAdulthood(): ?int { return $this->adulthood; }
    public function setAdulthood(?int $adulthood): static
    {
        $this->adulthood = $adulthood;
        return $this;
    }

    public function getLifetime(): ?int { return $this->lifetime; }
    public function setLifetime(?int $lifetime): static
    {
        $this->lifetime = $lifetime;
        return $this;
    }
}

src/Controller/RulesController.php
<?php

namespace App\Controller;

use App\Entity\Classes;
use App\Entity\Race;
use App\Entity\Skill;
use App\Repository\ClassesRepository;
use App\Repository\RaceRepository;
use App\Repository\SkillRepository;
use App\Repository\StatisticRepository;
use App\Repository\TalentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RulesController extends AbstractController
{
    #[Route('/race/{slug}', name: 'race')]
    public function race(
        string $slug,
        RaceRepository $raceRepository): Response
    {
        $race = $raceRepository->findOneBy(["slug" => $slug]);
        return $this->render('rules/race.html.twig', [
            'race' => $race
        ]);
    }

    #[Route('/classe/{slug}', name: 'class')]
    public function classe(
        string $slug,
        ClassesRepository $classesRepository,
        SkillRepository $skillRepository): Response
    {
        $class = $classesRepository->findOneBy(["slug" => $slug]);

        $skills = $skillRepository->findByClass( $class->getId());
        return $this->render('rules/classe.html.twig', [
            'classe' => $class,
            'skills' => $skills
        ]);
    }

    #[Route('/regles', name: 'teaser_rules')]
    public function rules(): Response
    {
        return $this->render('rules/rules.html.twig');
    }
    #[Route('/regles/repos', name: 'rules_rest')]
    public function restRule(): Response
    {
        return $this->render('rules/rest.html.twig');
    }
    #[Route('/regles/statistiques', name: 'rules_statistic')]
    public function statisticRule(StatisticRepository $statisticRepository): Response
    {
        $statistics = $statisticRepository->findAll();
        return $this->render('rules/statistic.html.twig', [
            "statistics" => $statistics
        ]);
    }
    #[Route('/regles/talents', name: 'rules_talents')]
    public function talentsRule(TalentRepository $talentRepository): Response
    {
        $talents = $talentRepository->findAll();
        return $this->render('rules/talents.html.twig', [
            "talents" => $talents
        ]);
    }
    #[Route('/regles/experience', name: 'rules_experiences')]
    public function experiencesRule(): Response
    {
        return $this->render('rules/experience.html.twig', [
        ]);
    }
    #[Route('/regles/combats', name: 'rules_fight')]
    public function fightRule(): Response
    {
        return $this->render('rules/fight.html.twig', [
        ]);
    }

    #[Route('/regles/jet-contre-la-mort', name: 'rules_death')]
    public function deathRule(): Response
    {
        return $this->render('rules/death.html.twig', [
        ]);
    }
    #[Route('/regles/blessure-grave', name: 'rules_injury')]
    public function injuryRule(): Response
    {
        return $this->render('rules/injury.html.twig', [
        ]);
    }


}

templates/rules/classe.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{classe.name}} | {{parent()}}{% endblock %}

{% block style %}
	<link rel="stylesheet" href="{{asset('style/dropdown.css')}}">
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="title">{{classe.name}}</h1>
		<div class="content">
			<h2 class="sub-title">Description</h2>
			<p class="pre-line">{{ classe.description}}</p>

			<h2 class="sub-title">Dé de niveau</h2>
			<div class="row">
				<div>
					<p>Point de vie</p>
					<p>{{ classe.dicePv}}</p>
				</div>
				<div>
					<p>Point de magie</p>
					<p>{{ classe.dicePc}}</p>
				</div>
				<div>
					<p>Points de combat</p>
					<p>{{ classe.dicePm}}</p>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<h2 class="sub-title-center">Compétences</h2>
		<div class="div-competence">
			{% for skill in skills %}
				{{skill|skillCard}}
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/rules/death.html.twig
{% extends 'base.html.twig' %}

{% block title %} Jet contre la mort | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">
        <h1 class="title">Jet contre la mort</h1>
        <div class="content">
            <h2 class="sub-title">Description</h2>
            <p>Lorsque vous atteignez 0 point de vie, 
            vous tombez au sol et vous vous retrouvez entre la vie et la mort.</p>
            <br>
            <p>Désormais, seul Mortaris va déterminer si vous allez survivre ou 
            mourir cependant selon votre état de santé vous aurez plus ou moins de 
            chance de mourir. Plus vous aurez de blessure grave plus aurez de 
            chance de mourir il y a trois cas de configuration lors de votre 
            jet de dé contre la mort.</p>
            <br>

            <h2 class="sub-title">Le Jet</h2>
            <h3>Si vous avez aucune ou une blessure :</h3>

            <p>Si votre résultat est entre 1 et 25 alors 
            il vous faudrat du repos pour vous en remmetre, 
            mais tout va bien pour vous</p>

            <p>Si votre résultat est entre 26 et 50 alors vous êtes vivant, 
            mais vous avez une blessure grave.</p>

            <p>Si votre résultat est entre 51 et 75 alors vous êtes mort, 
            mais il est possible d’utiliser un point de destin.</p>

            <p>Si votre résultat est à plus de 75 alors vous êtes morts 
            et les dieux ne pourront rien pour vous.</p>

            <br>
            <h3>Si vous avez 2 blessure :</h3>

            <p>Si le résultat est entre 6 et 25 vous êtes vivant, 
            mais votre état s’aggrave vous avez désormais 3 blessures graves.</p>
            <p>Si le résultat est entre 26 et 75 vous avez succombé à 
            vos blessures, mais les dieux vous accorde une nouvelle 
            chance grâce à un point de destin.</p>
            <br>
            <h3>Si vous avez 3 blessures</h3>
            <p>Si votre résultat dépasse 50 alors vos blessures ont eu raison de vous.</p>


        </div>
	</div>
{% endblock %}

templates/rules/experience.html.twig
{% extends 'base.html.twig' %}

{% block title %}Experience | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">

        <h1 class="title">Experience</h1>

        <div class="content">
            <h2 class="sub-title">Description</h2>
            <p>Expérience et le reflet de vos entraînements et de vos combats, 
            celle-ci représente votre apprentissage pour le talent en compétences 
            ainsi que votre amélioration physique globale.</p>
            <p>Lorsque vous gagnez des points d'expérience vous choisissez où investir 
            ces points. Cela peut être n’importe où dans un talent, 
            dans une compétence ou encore dans l’augmentation de niveaux 
            lorsque vous investissez des points ces derniers représentent les fruits 
            du potentiel entraînement. Lorsque vous atteignez le nombre de points 
            nécessaire, cela signifie que votre persévérance a porté ses fruits, 
            l’objet de cet entraînement se voit acquis sans délai.</p>
            <br>
            <h3>Exemple</h3>
            <p>Crom à 1000 points d’expérience en réserve, 
            il décide de dépenser 300 XP et les mettre dans le talent Lutte, 
            n’ayant se talent qu'au niveau débutant, 
            il passe désormais au niveau apprentis 
            de plus il souhaite débloquer la compétence double attaque, 
            il a déjà 600 XP sur cette compétence, 
            il lui reste donc 150 points à mettre pour débloquer sa compétence.</p>
            <p>Il reste maintenant à Crom 550 XP, mais pour le moment, 
            il ne sait pas quoi en faire, il décide alors de les garder en 
            réserve en attendant de savoir où les placer.</p>
            <br>
            <h3>Expliquation</h3>
            <p>Comme précisé précédemment, vous pouvez investir votre expérience dans trois catégories :
            </p>
            <br>
            <p>En premier, il y a bien sûr l’augmentation de niveau qui permet d’avoir accès à des nouveaux points de talent, de nouvelles compétences et des améliorations de statut.
            </p>
            <p>En second, vous pouvez augmenter vos points de talents cela vous permet d’avoir un meilleur bonus dans un talent.
            </p>
            <p>En dernier il y a les compétences à avoir lorsque vous passez un niveau, vous pouvez débloquer l’accès à des nouvelles compétences. Cependant, vous ne pouvez pas encore les utiliser. Vous devez avant cela investir de l'expérience pour pouvoir utiliser cette compétence.
            </p>
            <br>

            <h2 class="sub-title">Expérience dans les talents</h2>
            <p>Pour les talents, il y a 6 cas différents pour gagner un niveau, 
            ces 6 cas se composent en deux groupes. 
            Le premier groupe est pour les talents normaux et 
            le second est pour les talents de formation. 
            Le diffèrent cas sont décrits dans le tableau ci-dessous :</p>
            <table class="tableau">
                <thead>
                    <tr>
                        <th>Niveau</th>
                        <th>Experience</th>
                        <th>Bonus</th>
                    </tr>    
                </thead>
                <tbody>
                    <tr>
                        <th>Talents normaux</th>
                    </tr>
                    <tr>
                        <td>Apprenti</td>
                        <td>300</td>
                        <td>+5</td>
                    </tr>
                    <tr>
                        <td>Avancé</td>
                        <td>500</td>
                        <td>+10</td>
                    </tr>
                    <tr>
                        <td>Maître</td>
                        <td>800</td>
                        <td>+15</td>
                    </tr>
                    <tr>
                        <th>Talents de formation</th>
                    </tr>
                    <tr>
                        <td>Apprenti</td>
                        <td>1000</td>
                        <td>+5</td>
                    </tr>
                    <tr>
                        <td>Avancé</td>
                        <td>600</td>
                        <td>+10</td>
                    </tr>
                    <tr>
                        <td>Maître</td>
                        <td>900</td>
                        <td>+15</td>
                    </tr>
                </tbody>
            </table>

            <h2 class="sub-title">Augmentation de niveaux</h2>
            <p>Afin d’augmenter de niveaux, il faut investir un certain nombre 
            de points d'expérience. Le nombre de points peut varier en fonction de 
            la classe que vous choisirez, deux cas interviennent. 
            Le premier cas concerne l’assassin, le clerc, le guerrier, l’ingénieur et 
            le rôdeur. Le deuxième cas concerne l’herboriste, le mage et le prêtre.</p>

            <table class="tableau">
                <thead>
                    <tr>
                        <th>Experience cas 1</th>
                        <th>Experience cas 2</th>
                        <th>Niveau</th>
                        <th>Point de talent</th>
                        <th>Point de formation</th>
                        <th>Point de Statistique</th>
                        <th>Statut</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>-----</td>
                        <td>-----</td>
                        <td>1</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>NON</td>
                    </tr>
                    <tr>
                        <td>1000</td>
                        <td>700</td>
                        <td>2</td>
                        <td>2</td>
                        <td>0</td>
                        <td>0</td>
                        <td>NON</td>
                    </tr>
                    <tr>
                        <td>1500</td>
                        <td>1200</td>
                        <td>2</td>
                        <td>2</td>
                        <td>0</td>
                        <td>5</td>
                        <td>OUI</td>
                    </tr>
                    <tr>
                        <td>1750</td>
                        <td>1450</td>
                        <td>4</td>
                        <td>2</td>
                        <td>2</td>
                        <td>0</td>
                        <td>NON</td>
                    </tr>
                    <tr>
                        <td>2000</td>
                        <td>1700</td>
                        <td>5</td>
                        <td>3</td>
                        <td>1</td>
                        <td>10</td>
                        <td>NON</td>
                    </tr>
                    <tr>
                        <td>2250</td>
                        <td>1950</td>
                        <td>6</td>
                        <td>4</td>
                        <td>0</td>
                        <td>0</td>
                        <td>OUI</td>
                    </tr>
                    <tr>
                        <td>2600</td>
                        <td>2300</td>
                        <td>7</td>
                        <td>2</td>
                        <td>1</td>
                        <td>0</td>
                        <td>NON</td>
                    </tr>
                    <tr>
                        <td>2900</td>
                        <td>2600</td>
                        <td>8</td>
                        <td>1</td>
                        <td>2</td>
                        <td>5</td>
                        <td>NON</td>
                    </tr>
                    <tr>
                        <td>3500</td>
                        <td>3200</td>
                        <td>9</td>
                        <td>2</td>
                        <td>3</td>
                        <td>0</td>
                        <td>OUI</td>
                    </tr>
                    <tr>
                        <td>4000</td>
                        <td>3700</td>
                        <td>10</td>
                        <td>4</td>
                        <td>1</td>
                        <td>10</td>
                        <td>OUI</td>
                    </tr>
                </tbody>
            </table>
        </div>
	</div>
{% endblock %}

templates/rules/fight.html.twig
{% extends 'base.html.twig' %}

{% block title %} Combat | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">
        <h1 class="title">Combat</h1>
        <div class="content">
            <h2 class="sub-title">Initiatives</h2>
            <p>Les combats sont une phase qui se déroule en tour par tour. 
                Afin de connaître l'ordre de chaque combattant, 
                chacun d'entre eux doit faire un jet initiative. 
                il suffit pour cela de lancé 1D100, plus le résultat est petit 
                plus vous commencez tôt.</p>
            <p>Au début de chaque combat, chaque combattant doit faire un jet de dés 
                pour savoir qui prend l'initiative d'attaquer en premier.</p>
            <br>

            <h2 class="sub-title">Action</h2>
            <p>Lorsque c'est à votre tour de jouer, 
                vous avez le droit de faire une action. 
                Cette action peut être différentes choses comme attaquer un ennemi, 
                utiliser un objet ou interagir avec le décor. 
                Le joueur n'a accès qu'à une action par tour en plus de son déplacement.</p>
            <br>

            <h2 class="sub-title">Déplacement</h2>
            <p>Lors de votre tour, vous pouvez également vous déplacer. 
                Vous pouvez bouger et vous rendre où vous voulez sur le champ de 
                bataille à une portée de 9 mètres autour de vous. 
                (il est également possible de grimper.)</p>
            <br>

            <h2 class="sub-title">Réaction</h2>
            <p>Lors d'un tour d’un autre joueur ou d’un ennemi, 
                il est possible dans certains cas de réagir à l’action de ce personnage 
                la réaction ce ne présente pas toujours au joueur. 
                La réaction se déclenche grâce à une compétence ou à une action d’un 
                personnage se trouvant à proximité.</p>
            <br>

            <h2 class="sub-title">Critique</h2>
            <p>Lors des combats, et plus précisément, lors des attaques, 
                vous devez lancer un jet d’attaque afin de savoir si vous touchez 
                l’adversaire. Lorsque vous lancez votre dé, il peut y avoir des 
                résultats spéciaux : si le résultat est entre 1 et 5 alors vous avez 
                fait une réussite critique, mais si vous faites entre 96 et 100 alors 
                vous avez fait un échec critique.</p>
            <br>

            <p>Succès critique : lorsqu’une attaque fait une réussite critique, 
                votre coup a non seulement touché votre cible, mais en plus, 
                vous l’avez sûrement blessé gravement. 
                Lorsque vous faites votre jet de dégâts, 
                les dégâts de base sont multipliés par 2.</p>
            <br>

            <p>Échec critique : lorsque votre de jet d’attaques fait un échec critique 
                alors votre coup ne touche pas sa cible. De plus, 
                à cause de votre maladresse, une conséquence vient s’ajouter. 
                (un allié touché se prend le coup, vous trébuchez, etc.)</p>
        </div>
	</div>
{% endblock %}

templates/rules/injury.html.twig
{% extends 'base.html.twig' %}

{% block title %} Blessure Grave | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">
        <h1 class="title">Blessure Grave</h1>
        <div class="content">
            <h2 class="sub-title">Description</h2>
            
            <p>Durant les combats, il arrive fréquemment que vous vous blessiez, 
            ces blessures sont en général des égratignures et des coupures. 
            Mais il arrive parfois que des coups soient beaucoup plus violents et 
            puissent vous casser des os ou encore vous toucher des organes 
            vitaux dans ce cas-là, vous obtenez ce qu'on appelle une blessure grave. 
            Comme son nom l'indique, les blessures graves sont des blessures qui vont 
            fortement impacter votre vitalité à court et moyen terme.</p>
            <br>

            <h2 class="sub-title">Comment soigner une blessure grave ?</h2>
    
            <p>La réponse est simple, avec du temps ! 
            La magie est certes puissante sur guintuaris, 
            mais elle ne permet pas de faire de miracle. Seul le temps peut 
            faire cela et parfois seul, il ne suffit pas. Pour certaines blessures 
            (les grosses plaies notamment), il sera important de se reposer pour que 
            les soins soient efficaces. Si vous ne vous reposez pas votre plaie 
            guérira pas ou même pire elle s'aggravera.</p>
        
            <br>
            <p>Il est aussi possible d’aggraver une blessure si 
            vous ne faites pas attention, par exemple si vous portez une 
            charge lourde alors que vous avez un bras cassé, 
            il se peut que la blessure à votre bras s’aggrave et que par 
            la suite vous ne soyez plus en mesure d’utiliser votre bras.</p>

            <br>
            <h3>Exemple</h3>
            <p>Falgram et un citrinzi et il se prend un violent coup sur 
            le thorax lui brisant 6 côtes, désormais avec cette blessure 
            grave Falgram aura besoin de plusieurs semaines pour 
            qu’il puisse guérir complètement de ces blessures. 
            Avec une telle blessure, Falgram aura du mal à faire de simples 
            actions comme courir ou même viser avec son pistolet 
            (malus sur les jets physique). Si Falgram se met à courir après 
            2 semaines de repos ce dernier a encore du mal à courir 
            correctement s'il persiste sa blessure peut s’aggraver et 
            empirer ces fractures et s'il persiste encore, 
            il pourrait même perforer un poumon !</p>

            <br>
            <p>En fonction de la blessure, les talents et les malus peuvent varier.</p>
            <p>Un malus débute à 5 points et peut aller jusqu'à 20 points 
            selon la gravité et le niveau de maîtrise. 
            (plus le niveau de maîtrise est élevé, moins le malus sera élevé.)</p>
            <p>Les talents quant à eux seront principalement des malus physique, 
            mais sur certaines blessures comme une commotion cérébrale 
            peuvent affecter les capacités intellectuelles sont elles aussi affectées.</p>

            <br>
            <p>Lorsque vous recevez une blessure grave, 
            vous recevez également un malus associé à cette blessure, 
            ce malus devrait baisser avec le temps si vous vous reposez correctement. 
            Mais il peut augmenter si votre blessure s’aggrave.</p>

            <br>
            <p>Si vous recevez une troisième trois blessure grave dans un temps 
            courts coûts entre le premier et le troisième, 
            vous tomberez inconscient et vous devrez alors lancer un 
            jet de dé contre la mort, car oui vous risquez de mourir dû au 
            trop grand nombre de blessure.</p>

            <br>
            <p>Ce module de règle est très arbitraire et dépendra uniquement 
            du maître du jeu et de ces décisions.</p>
        </div>
	</div>
{% endblock %}

templates/rules/race.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{race.name}} | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="title">{{race.name}}</h1>

		<div class="content">
			<h2 class="sub-title">Description</h2>
			<p class="pre-line">{{ race.description}}

			taille minimum-maximum : {{(race.minHeight / 100)|number_format(2, 'm','')}}-{{(race.maxHeight / 100)|number_format(2, 'm','')}}
			poids moyens : {{race.averageWheight}} kg
			durèe de vie : {{race.lifetime}} ans
			âge adulte : {{race.adulthood}} ans
			</p>

			<h2 class="sub-title">Aptitude sociale</h2>
			<p class="pre-line">{{ race.socialAbility}}</p>
			
			<h2 class="sub-title">Aptitude Physique</h2>
			<p class="pre-line">{{ race.physicalAbility}}</p>
			
			<h2 class="sub-title">Bonus</h2>
			<p class="pre-line">{{ race.bonus}}</p>
		</div>
	</div>
{% endblock %}

templates/rules/rest.html.twig
{% extends 'base.html.twig' %}

{% block title %}Repos | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">

        <h1 class="title">Repos</h1>
        <div class="content">

            <h2 class="sub-title">Description</h2>
            <p>Afin de regagner des forces après des combats, 
            les joueurs peuvent décider de prendre soit un temps de repos 
            soit un temps de sommeil, ces deux temps permettent aux joueurs de regagner 
            des ressources afin d'être en meilleure forme pour
            le combat ou le voyage qui les attend.</p>
            <br>
            <h2 class="sub-title">Temps de repos</h2>
            <p>Le temps de repos est un temps où le personnage décide 
            de se reposer pendant un minimum de 2h. 
            Durant ce temps, votre personnage ne fait aucune activité fatigante, 
            cela va lui permettre de se ressourcer et de récupérer des forces pour 
            la suite de la journée.</p>
            <br>
            <p>Pour 2h de repos, votre personnage regagne pour chacune de 
            ces ressources un dé de niveau pour chaque deux niveaux 
            ( 1d pour niveau 1, 2 et 3, 2d pour le niveau 4 et 5 ...).</p>

            <p> Puis pour chaque 2 heure en plus, il regagne une dizaine 
            de la statistique associées à sa ressource.</p>
            <br>
            <h3>Exemple</h3>
            <p>Crom est un guerrier de niveau 6 qui se repose 4h. Il peut donc lancer 3d12 pour sa vie, 3d4 pour sa magie et 3d6 pour ces points de combat puis pour le 2h de plus il peut gagner 4 points de vie (40 de constitution) 5 points de combat (50 de force) et 2 points de magie (20 d’intelligence)</p>
            <br>
            <h2 class="sub-title">Temps de sommeil</h2>
            <p>Le temps de sommeil quant à lui, est un temps où le personnage 
            doit dormir sur une durée de minimum le sommeil est très important 
            de se ressourcer auprès des dieux.</p>

            <p>Au bout de 6h de sommeil, le joueur pourra recouvrer l'intégralité de 
            ses points de vie et pour recouvrer la moitié de ce point de magie 
            ainsi que de ses points d'endurance.</p>
            <br>
            <h2 class="sub-title">Fatigue</h2>
            <p>Il est nécessaire pour un personnage normal de faire 
            un temps de sommeil par jour si cela n'est pas fait, 
            ce dernier sera donc affaibli.</p>
            <br>
            <h3>Fatigue 1</h3>
            <p>Sans une bonne nuit de sommeil, vous ne pouvez pas exprimer 
            vos talents, votre état mental et physique vous empêche de 
            les utiliser.</p>
            <p>Aucun talent en place</p>
            <br>
            <h3>Fatigue 2</h3>
            <p>Désormais, c’est votre santé qui en prend un coup, 
            vos statistiques se voient réduites de 10 points et 
            vos points de vie se voient réduits d’un quart.</p>
            <p>Malus de 10 et pu max réduit de 1/4</p>
            <br>
            <h3>Fatigue 3</h3>
            <p></p>
        </div>
	</div>
{% endblock %}

templates/rules/rules.html.twig
{% extends 'base.html.twig' %}

{% block title %} Les regles | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="title">Regles de jeu</h1>
		<div class="content">
			<p>les regles de jeu vont bientt arrivé sur Guintuaris.fr.</p>
			<p> vous pourrez consulter toute les regles de jeu et les lexique en deux clique grace a cette page.</p>
			<h2 class="sub-title">Soyer patient cette fonctonalité arrive bientot</h2>
		</div>
	</div>
{% endblock %}

templates/rules/statistic.html.twig
{% extends 'base.html.twig' %}

{% block title %}Statistique | {{parent()}}{% endblock %}

{% block body %}
	<div class="container">

        <h1 class="title">Statistique</h1>
        <div class="content">
            <h2 class="sub-title">Description</h2>
            <p>Les statistiques représentent chacune un aspect physique et/ou 
            intellectuelle de votre personnage, elles sont au nombre de six 
            et chacune d’elles sont indépendantes des autres.</p>
            <br>
            {% for stat in statistics %}
                <h2 class="sub-title">{{stat.name}}</h2>
                <p>{{stat.description}}</p>
                <br>
            {% endfor %}
        </div>
	</div>
{% endblock %}